In [ ]:
pip install advertools

In [1]:
import advertools as adv

In [2]:
kw_df = adv.kw_generate(products=['TV','TCL'],
                words=['28-43 inch', '46-58 inch', '30% discount','35% discount','25% discount','25000₹','35000₹','45000₹','55000₹','cheap','buy'],
                match_types=['Exact','Phrase','Modified'],
                order_matters=False,
                max_len=2,
                campaign_name='Casual users',
               )

In [3]:
kw_df

        Campaign Ad Group           Keyword Criterion Type      Labels
0   Casual users       Tv     TV 28-43 inch          Exact  28-43 Inch
1   Casual users       Tv     TV 28-43 inch         Phrase  28-43 Inch
2   Casual users       Tv  +TV +28-43 +inch          Broad  28-43 Inch
3   Casual users       Tv     TV 46-58 inch          Exact  46-58 Inch
4   Casual users       Tv     TV 46-58 inch         Phrase  46-58 Inch
..           ...      ...               ...            ...         ...
61  Casual users      Tcl         TCL cheap         Phrase       Cheap
62  Casual users      Tcl       +TCL +cheap          Broad       Cheap
63  Casual users      Tcl           TCL buy          Exact         Buy
64  Casual users      Tcl           TCL buy         Phrase         Buy
65  Casual users      Tcl         +TCL +buy          Broad         Buy

[66 rows x 5 columns]

In [4]:
def func(x):
    if 'inch' in x:
        return "size"
    elif 'QLED' in x:
        return "resolution"
    elif 'Ultra HD' in x:
        return "resolution"
    elif 'Tizen' in x:
        return "techie"
    else:
        return 'potential buyer'
    

kw_df['Ad Group'] = kw_df['Keyword'].apply(func)

In [5]:
def func1(criterion,keyword):
    if criterion=='Exact':
        return "["+keyword+"]"
    elif criterion=='Broad':
        return keyword
    else:
        return "'"+keyword+"'"
    
    
kw_df['Keyword'] = kw_df.apply(lambda x: func1(x['Criterion Type'], x['Keyword']),axis=1)

In [6]:
kw_df

        Campaign         Ad Group           Keyword Criterion Type      Labels
0   Casual users             size   [TV 28-43 inch]          Exact  28-43 Inch
1   Casual users             size   'TV 28-43 inch'         Phrase  28-43 Inch
2   Casual users             size  +TV +28-43 +inch          Broad  28-43 Inch
3   Casual users             size   [TV 46-58 inch]          Exact  46-58 Inch
4   Casual users             size   'TV 46-58 inch'         Phrase  46-58 Inch
..           ...              ...               ...            ...         ...
61  Casual users  potential buyer       'TCL cheap'         Phrase       Cheap
62  Casual users  potential buyer       +TCL +cheap          Broad       Cheap
63  Casual users  potential buyer         [TCL buy]          Exact         Buy
64  Casual users  potential buyer         'TCL buy'         Phrase         Buy
65  Casual users  potential buyer         +TCL +buy          Broad         Buy

[66 rows x 5 columns]

In [7]:
kw_df

        Campaign         Ad Group           Keyword Criterion Type      Labels
0   Casual users             size   [TV 28-43 inch]          Exact  28-43 Inch
1   Casual users             size   'TV 28-43 inch'         Phrase  28-43 Inch
2   Casual users             size  +TV +28-43 +inch          Broad  28-43 Inch
3   Casual users             size   [TV 46-58 inch]          Exact  46-58 Inch
4   Casual users             size   'TV 46-58 inch'         Phrase  46-58 Inch
..           ...              ...               ...            ...         ...
61  Casual users  potential buyer       'TCL cheap'         Phrase       Cheap
62  Casual users  potential buyer       +TCL +cheap          Broad       Cheap
63  Casual users  potential buyer         [TCL buy]          Exact         Buy
64  Casual users  potential buyer         'TCL buy'         Phrase         Buy
65  Casual users  potential buyer         +TCL +buy          Broad         Buy

[66 rows x 5 columns]

In [8]:
# Save the final keywords to a CSV file
kw_df.to_excel('casual_user.xlsx',index=False)

# View a summary of our campaign work
summary = kw_df.groupby(['Ad Group', 'Criterion Type'])['Keyword'].count()
summary

Ad Group         Criterion Type
potential buyer  Broad             18
                 Exact             18
                 Phrase            18
size             Broad              4
                 Exact              4
                 Phrase             4
Name: Keyword, dtype: int64